use LanguageServer::Protocol::Constant::DiagnosticSeverity as LSPDiagnosticSeverity
use LanguageServer::Protocol::Interface::Diagnostic as LSPDiagnostic

module Steep
  module Diagnostic
    class LSPFormatter
      module LSP = LanguageServer::Protocol

      type config = Hash[singleton(Diagnostic::Ruby::Base) | singleton(Diagnostic::Signature::Base), severity?]

      type severity = :error | :warning | :information | :hint

      attr_reader config: config

      attr_reader default_severity: severity

      # The directory the relative paths of the locations are resolved from, to make the URIs of the related locations
      attr_reader base_dir: Pathname?

      ERROR: :error

      WARNING: :warning

      INFORMATION: :information

      HINT: :hint

      def initialize: (?config config, ?default_severity: severity, ?base_dir: Pathname?) -> void

      def validate_class: (Class klass) -> void

      def validate_severity: (Class | :default klass, severity?) -> void

      def format: (Diagnostic::Ruby::Base | Diagnostic::Signature::Base) -> LSPDiagnostic::json?

      def severity_for: (Diagnostic::Ruby::Base | Diagnostic::Signature::Base) -> LSPDiagnosticSeverity::t?

      # Returns the `relatedInformation` of the related locations of the diagnostic
      #
      # The locations in files with relative paths are skipped if `base_dir` is not given.
      #
      def related_information: (Diagnostic::Signature::Base) -> Array[LanguageServer::Protocol::Interface::DiagnosticRelatedInformation::json]
    end
  end
end
