module Steep
  module Diagnostic
    module Signature
      class Base
        include Helper

        attr_reader location: untyped

        def initialize: (location: untyped) -> void

        def header_line: () -> untyped

        def detail_lines: () -> nil

        def diagnostic_code: () -> ::String

        def path: () -> untyped
      end

      class SyntaxError < Base
        attr_reader exception: untyped

        def initialize: (untyped exception, location: untyped) -> void

        def self.parser_syntax_error_message: (untyped exception) -> ::String

        def header_line: () -> untyped
      end

      class DuplicatedDeclaration < Base
        attr_reader type_name: untyped

        def initialize: (type_name: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class UnknownTypeName < Base
        attr_reader name: untyped

        def initialize: (name: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class InvalidTypeApplication < Base
        attr_reader name: untyped

        attr_reader args: untyped

        attr_reader params: untyped

        def initialize: (name: untyped, args: untyped, params: untyped, location: untyped) -> void

        def header_line: () -> untyped
      end

      class UnsatisfiableTypeApplication < Base
        attr_reader type_name: untyped

        attr_reader type_arg: untyped

        attr_reader type_param: untyped

        def initialize: (type_name: untyped, type_arg: untyped, type_param: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class InvalidMethodOverload < Base
        attr_reader class_name: untyped

        attr_reader method_name: untyped

        def initialize: (class_name: untyped, method_name: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class UnknownMethodAlias < Base
        attr_reader class_name: untyped

        attr_reader method_name: untyped

        def initialize: (class_name: untyped, method_name: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class DuplicatedMethodDefinition < Base
        attr_reader class_name: untyped

        attr_reader method_name: untyped

        def initialize: (class_name: untyped, method_name: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class RecursiveAlias < Base
        attr_reader class_name: untyped

        attr_reader names: untyped

        attr_reader location: untyped

        def initialize: (class_name: untyped, names: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class RecursiveAncestor < Base
        attr_reader ancestors: untyped

        def initialize: (ancestors: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class SuperclassMismatch < Base
        attr_reader name: untyped

        def initialize: (name: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class GenericParameterMismatch < Base
        attr_reader name: untyped

        def initialize: (name: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class InvalidVarianceAnnotation < Base
        attr_reader name: untyped

        attr_reader param: untyped

        def initialize: (name: untyped, param: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class ModuleSelfTypeError < Base
        attr_reader name: untyped

        attr_reader ancestor: untyped

        attr_reader relation: untyped

        def initialize: (name: untyped, ancestor: untyped, relation: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      # The error is raised when a class variable is defined in both `class_name` and `other_class_name`
      #
      class ClassVariableDuplicationError < Base
        attr_reader class_name: RBS::TypeName
        attr_reader other_class_name: RBS::TypeName
        attr_reader variable_name: Symbol

        def initialize: (class_name: RBS::TypeName, other_class_name: RBS::TypeName, variable_name: Symbol, location: RBS::Location[untyped, untyped]) -> void

        def header_line: () -> String
      end


      class InstanceVariableTypeError < Base
        attr_reader name: untyped

        attr_reader variable: untyped

        attr_reader var_type: untyped

        attr_reader parent_type: untyped

        def initialize: (name: untyped, location: untyped, var_type: untyped, parent_type: untyped) -> void

        def header_line: () -> ::String
      end

      class MixinClassError < Base
        attr_reader member: untyped

        attr_reader type_name: untyped

        def initialize: (location: untyped, member: untyped, type_name: untyped) -> void

        def header_line: () -> ::String

        private

        def mixin_name: () -> untyped
      end

      # A class definition has a module as its super class
      #
      class InheritModuleError < Base
        attr_reader super_class: RBS::AST::Declarations::Class::Super

        def initialize: (RBS::AST::Declarations::Class::Super) -> void

        def header_line: () -> String
      end

      class UnexpectedError < Base
        attr_reader message: untyped

        def initialize: (message: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class RecursiveTypeAlias < Base
        attr_reader alias_names: untyped

        def initialize: (alias_names: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      class NonregularTypeAlias < Base
        attr_reader type_name: untyped

        attr_reader nonregular_type: untyped

        def initialize: (type_name: untyped, nonregular_type: untyped, location: untyped) -> void

        def header_line: () -> ::String
      end

      def self.from_rbs_error: (untyped error, factory: untyped) -> untyped
    end
  end
end
