use RBS::Location, RBS::TypeName, RBS::Environment
use RBS::AST::Ruby as RubyAST
use RBS::AST

module Steep
  module Services
    module HoverProvider
      type RBS::content = TypeAliasContent | ClassTypeContent | InterfaceTypeContent

      class RBS
        attr_reader service: TypeCheckService

        def initialize: (service: TypeCheckService) -> void

        def project: () -> Project

        def content_for: (target: Project::Target, path: Pathname, line: Integer, column: Integer) -> RBS::content?

        def content_for_type_name: (TypeName, env: Environment, location: Location[untyped, untyped]) -> RBS::content?
      end
    end
  end
end
