module Steep
  module Services
    module HoverProvider
      module SingletonMethods
        def content_for: (service: TypeCheckService, path: Pathname, line: Integer, column: Integer) -> (Ruby::content | RBS::content | nil)
      end

      extend SingletonMethods
    end
  end
end
