# disabled for rubocop-rspec

RSpec/DescribeClass:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VoidExpect:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false
