# module Steep
#   module AST
#     class TypeParams
#       attr_reader location: untyped

#       attr_reader variables: untyped

#       def initialize: (variables: untyped, ?location: untyped?) -> void
#     end
#   end
# end
