module Steep
  module Server
    # Defines custom LSP methods
    module CustomMethods
      # Notification with params of files and the contents, sent from master to workers
      #
      module FileLoad
        METHOD: String

        type params = {
          content: Hash[String, ChangeBuffer::content]
        }

        def self.notification: (params) -> untyped
      end

      # Notification with parames of a file name and its contents, sent from master to workers
      #
      module FileReset
        METHOD: String

        type params = { uri: String, content: String }

        def self.notification: (params) -> untyped
      end

      # Notification to start type checking, sent from client to master
      #
      module TypeCheck
        METHOD: String

        type params = { guid: String? }

        def self.notification: (params) -> untyped
      end

      # Notification to start type checking, sent from the master to workers
      #
      module TypeCheck__Start
        METHOD: String

        type params = Master::TypeCheckRequest::json

        def self.notification: (params) -> untyped
      end

      # Notification to report progress of type checking, sent from workers to master
      #
      module TypeCheck__Progress
        METHOD: String

        type params = { guid: String, path: String }

        def self.notification: (params) -> untyped
      end

      # The command name to start stats of type checking, sent from client to master and master to workers
      #
      STATS: String
    end
  end
end
