use LanguageServer::Protocol::Interface::Diagnostic as LSPDiagnostic
use Steep::Project::Target, Steep::Project::Group

module Steep
  module Server
    # TypeCheckController remembers changed files, keep track of open editors, and make a TypeCheckRequest that contains list of all files to be type checked
    #
    # ```rb
    # controller = TypeCheckController.new(project: project)
    #
    # controller.add_dirty_code_path(file_path)    # Remember that the path is changed
    # controller.open_path(file_path)              # Remember that an editor opens the path
    # controller.make_request(...)                 # Make an instance of TypeCheckRequest that contains list of all paths to type check
    # ```
    #
    class TypeCheckController
      # A type checking request keeps track of the progress of the type checking
      #
      # It has `path` of all files to be type checked and records which path is already checked.
      #
      class Request
        attr_reader guid: String

        attr_reader work_done_progress: WorkDoneProgress

        # Pair of target name and path
        type target_and_path = [Symbol, Pathname]

        # The path of RBS files of libraries
        attr_reader library_paths: Set[target_and_path]

        # The path of signature files
        attr_reader signature_paths: Set[target_and_path]

        # The path of Ruby code files
        attr_reader code_paths: Set[target_and_path]

        # The path of inline RBS files
        attr_reader inline_paths: Set[target_and_path]

        # The path of files that is opened by the editor
        attr_reader priority_paths: Set[Pathname]

        # The path of files that are type checked already
        attr_reader checked_paths: Set[target_and_path]

        # The time when the request object is created
        attr_reader started_at: Time

        # `true` to report the progress to the client
        attr_reader report_progress: bool

        # `true` to send a response to the client
        #
        # Defaults to `false`.
        #
        attr_accessor needs_response: bool

        def initialize: (guid: String, progress: WorkDoneProgress) -> void

        private def uri: (Pathname path) -> URI::File

        # Pair of target name and path string
        #
        type target_path_string = [String, String]

        type json = {
          guid: String,
          library_uris: Array[target_path_string],
          signature_uris: Array[target_path_string],
          code_uris: Array[target_path_string],
          inline_uris: Array[target_path_string],
          priority_uris: Array[String]
        }

        def as_json: (assignment: Services::PathAssignment) -> json

        def total: () -> Integer

        # Returns true if no path is registered to the request
        #
        def empty?: () -> bool

        def percentage: () -> Integer

        # Enumerates all paths included in the request
        #
        def each_path: () { (Pathname) -> void } -> void
                     | () -> Enumerator[Pathname]

        def each_target_path: () { (target_and_path) -> void } -> void
                            | () -> Enumerator[target_and_path]

        def checking_path?: (target_and_path) -> bool

        # Mark a path is type checked
        def checked: (Pathname path, Target) -> void

        def finished?: () -> bool

        def each_unchecked_path: () { (Pathname) -> void } -> void
                               | () -> Enumerator[Pathname]

        def each_unchecked_target_path: () { (target_and_path) -> void } -> void
                                      | () -> Enumerator[target_and_path]

        def each_unchecked_code_target_path: () { (target_and_path) -> void } -> void
                                           | () -> Enumerator[target_and_path]

        def each_unchecked_library_target_path: () { (target_and_path) -> void } -> void
                                              | () -> Enumerator[target_and_path]

        def each_unchecked_signature_target_path: () { (target_and_path) -> void } -> void
                                                | () -> Enumerator[target_and_path]

        def each_unchecked_inline_target_path: () { (target_and_path) -> void } -> void
                                              | () -> Enumerator[target_and_path]

        # Set `#report_progress` and return self, defaults to `true`
        #
        def report_progress!: (?bool) -> self

        # Merges another request into this request
        def merge!: (Request) -> self

        private def assigned_uris: (Services::PathAssignment, Set[target_and_path]) -> Array[target_path_string]
      end

      # The group of files that should be type checked/validated
      type group = Target | Group

      attr_reader project: Project

      # Set of open file paths
      #
      attr_reader open_paths: Set[Pathname]

      # Set of groups that has activated since last type checking request
      #
      attr_reader new_active_groups: Set[group]

      # Set of all active groups
      #
      attr_reader active_groups: Set[group]

      # Set of Ruby code paths that content is changed since last type checking request
      attr_reader dirty_code_paths: Set[Pathname]

      # Set of RBS file paths that content is changed since last type checking request
      attr_reader dirty_signature_paths: Set[Pathname]

      # Set of inline RBS file paths that content is changed since last type checking request
      attr_reader dirty_inline_paths: Set[Pathname]

      attr_reader inline_path_changes: InlineSourceChangeDetector

      attr_reader files: TargetGroupFiles

      def initialize: (project: Project) -> void

      # Load files from commandline_args
      #
      def load: (command_line_args: Array[String]) { (Hash[String, ChangeBuffer::content]) -> void } -> void

      def code_path?: (Pathname path) -> bool

      def signature_path?: (Pathname path) -> bool

      def inline_path?: (Pathname path) -> bool

      def add_dirty_code_path: (Pathname path) -> void

      def add_dirty_signature_path: (Pathname path) -> void

      def add_dirty_inline_path: (Pathname path, String | Array[Services::ContentChange] update) -> void

      def open_inline_path: (Pathname path, String content) -> void

      def each_dirty_path: () { (Pathname) -> void } -> void
                           | () -> Enumerator[Pathname]

      # Delete everything from changed_paths
      #
      # priority_paths are not updated.
      #
      def reset: () -> void

      # Notify a path is opened
      #
      # Returns a group if the path is the first open path of the group.
      #
      def open_path: (Pathname path) -> void

      # Notify a path is closed
      #
      def close_path: (Pathname path) -> void

      # Yields groups (targets) that has open paths
      #
      def each_active_group: () { (group) -> void } -> void
                           | () -> Enumerator[group]

      # Returns true if given group (group or target) includes priority path
      #
      def active_group?: (group) -> bool

      # Returns a TypeCheckRequest that contains pending paths
      #
      # * This method also resets the controller status
      # * `progress:` is a `WorkDoneProgress` object to report the progress of the type checking
      # * Returns `nil` when no type checking is needed
      #
      # Resets after making the request.
      #
      def make_request: (?guid: String, progress: WorkDoneProgress) -> Request?

      # Returns a TypeCheckRequest that contains all of the paths of the project
      #
      # * This method also resets the controller status.
      # * `progress:` is a `WorkDoneProgress` object to report the progress of the type checking.
      #
      # Resets after making the request.
      #
      def make_all_request: (?guid: String, progress: WorkDoneProgress) -> Request

      # Returns a request to type check Ruby code and RBS type signatures of given groups
      #
      # Removes the specified groups from `new_active_groups` and delete type checked paths from `dirty_paths`.
      # Raises an exception if the groups are empty.
      #
      # A group name can be a target name or a group name.
      #
      # * `lib`      => A target name in the project
      # * `lib.core` => A group name in the project
      #
      def make_group_request: (Array[String] groups, ?guid: String, progress: WorkDoneProgress) -> Request

      # Returns true if the group is unreferenced
      #
      private def unreferenced?: (group) -> bool

      private def group_of: (Pathname path) -> group?

      private def target_of: (Pathname path) -> Target?
    end
  end
end
