source "https://rubygems.org"

gem 'steep', git: "https://github.com/soutaro/steep.git", branch: "master", require: false
gem "mutex_m"
gem "rbs-inline", require: false
gem "ruby-lsp", require: false
gem "debug", require: false, platform: :mri
gem "minitest"
