source "https://rubygems.org"

gem 'steep', "~> 1.10.0.pre", require: false
gem "mutex_m"
gem "rbs-inline", require: false
gem "ruby-lsp", require: false
gem "debug", require: false, platform: :mri
gem "minitest"
