class BlockBodyTypeMismatch
  def foo: () { () -> Integer } -> void
end

class MethodDefinitionMissing
  def foo: () -> void

  attr_reader    bar: untyped
  attr_writer    baz: untyped
  attr_accessor  qux: untyped
end

class UnexpectedDynamicMethod
  def bar: () -> void
end

class UnknownConstantAssigned
end

class UnexpectedKeyword
  def foo: (foo: Integer) -> void
end

class MissingKeyword
  def foo: (?String, foo: Integer, ?bar: Symbol) -> void
end
