module Steep
  module AST
    module Types
      class Boolean
        extend SharedInstance[Boolean]
        
        def ==: (untyped other) -> bool

        def hash: () -> Integer

        alias eql? ==

        def subst: (Interface::Substitution) -> Boolean

        def to_s: () -> String

        include Helper::NoFreeVariables

        include Helper::NoChild

        def level: () -> Array[Integer]

        def back_type: () -> t
      end
    end
  end
end
