module Steep
  module AST
    module Types
      class Bot
        extend SharedInstance[Bot]
        
        def ==: (untyped other) -> bool

        def hash: () -> Integer

        alias eql? ==

        def subst: (Interface::Substitution) -> Bot

        def to_s: () -> String

        include Helper::NoFreeVariables

        include Helper::NoChild

        def level: () -> Array[Integer]
      end
    end
  end
end
