module Steep
  module AST
    module Types
      class Class
        attr_reader location: untyped

        def initialize: (?location: untyped?) -> void

        def to_s: () -> String

        def ==: (untyped other) -> bool

        def hash: () -> Integer

        alias eql? ==

        def subst: (Interface::Substitution s) -> t

        @@fvs: Set[variable]
        def free_variables: () -> Set[variable]

        include Helper::NoChild

        def level: () -> Array[Integer]

        def with_location: (untyped new_location) -> Class

        self.@instance: Class
        def self.instance: () -> Class
      end
    end
  end
end
