module Steep
  module AST
    module Types
      class Instance
        attr_reader location: untyped

        def initialize: (?location: untyped?) -> void

        def ==: (untyped other) -> bool

        def hash: () -> Integer

        alias eql? ==

        def subst: (Interface::Substitution s) -> t

        @@fvs: Set[variable]
        def free_variables: () -> Set[variable]

        include Helper::NoChild

        def to_s: () -> String

        def level: () -> Array[Integer]

        def with_location: (untyped new_location) -> untyped

        self.@instance: Instance
        def self.instance: () -> Instance
      end
    end
  end
end
