module Steep
  module AST
    module Types
      class Literal
        attr_reader location: untyped

        attr_reader value: untyped

        def initialize: (value: untyped, ?location: untyped?) -> void

        def ==: (untyped other) -> untyped

        def hash: () -> untyped

        alias eql? ==

        def subst: (untyped s) -> self

        def to_s: () -> untyped

        include Helper::NoFreeVariables

        include Helper::NoChild

        def level: () -> ::Array[0]

        def with_location: (untyped new_location) -> untyped

        def back_type: () -> untyped
      end
    end
  end
end
