module Steep
  module AST
    module Types
      class Literal
        attr_reader location: untyped

        attr_reader value: untyped

        def initialize: (value: untyped, ?location: untyped?) -> void

        def ==: (untyped other) -> bool

        def hash: () -> Integer

        alias eql? ==

        def subst: (Interface::Substitution s) -> self

        def to_s: () -> String

        include Helper::NoFreeVariables

        include Helper::NoChild

        def level: () -> Array[Integer]

        def with_location: (untyped new_location) -> self

        def back_type: () -> AST::Types::Name::Instance
      end
    end
  end
end
