module Steep
  module AST
    module Types
      class Self
        attr_reader location: untyped

        def initialize: (?location: untyped?) -> void

        def ==: (untyped other) -> untyped

        def hash: () -> untyped

        alias eql? ==

        def to_s: () -> "self"

        include Helper::NoChild

        def subst: (untyped s) -> untyped

        def free_variables: () -> untyped

        def level: () -> Array[Integer]

        def with_location: (untyped new_location) -> untyped

        self.@instance: Self
        def self.instance: () -> Self
      end
    end
  end
end
