module Steep
  module AST
    module Types
      class Self
        extend SharedInstance[Self]

        def ==: (untyped other) -> bool

        def hash: () -> Integer

        alias eql? ==

        def to_s: () -> String

        include Helper::NoChild

        def subst: (Interface::Substitution s) -> t

        @@fvs: Set[variable]
        def free_variables: () -> Set[variable]

        def level: () -> Array[Integer]
      end
    end
  end
end
