module Steep
  module AST
    module Types
      class Union
        attr_reader types: Array[t]

        attr_reader location: untyped

        def initialize: (types: Array[t], ?location: untyped) -> void

        def self.build: (types: Array[t], ?location: untyped) -> t

        def ==: (untyped other) -> bool

        @hash: Integer
        def hash: () -> Integer

        alias eql? ==

        def subst: (Interface::Substitution s) -> t

        def to_s: () -> ::String

        @fvs: Set[variable]
        def free_variables: () -> Set[variable]

        def each_child: () { (t) -> void } -> void
                      | () -> Enumerator[t, void]

        include Helper::ChildrenLevel

        def level: () -> Array[Integer]

        def with_location: (untyped new_location) -> Union
      end
    end
  end
end
