module Steep
  module AST
    module Types
      class Union
        attr_reader types: Array[t]

        def initialize: (types: Array[t]) -> void

        def self.build: (types: Array[t]) -> t

        def ==: (untyped other) -> bool

        @hash: Integer
        def hash: () -> Integer

        alias eql? ==

        def subst: (Interface::Substitution s) -> t

        def to_s: () -> ::String

        @fvs: Set[variable]
        def free_variables: () -> Set[variable]

        def each_child: () { (t) -> void } -> void
                      | () -> Enumerator[t, void]

        def map_type: () { (t) -> t } -> t

        include Helper::ChildrenLevel

        def level: () -> Array[Integer]

        def with_location: (untyped) -> Tuple
      end
    end
  end
end
