module Steep
  module AST
    module Types
      class Void
        attr_reader location: untyped

        def initialize: (?location: untyped?) -> void

        def ==: (untyped other) -> untyped

        def hash: () -> untyped

        alias eql? ==

        def subst: (untyped s) -> self

        def to_s: () -> "void"

        include Helper::NoFreeVariables

        include Helper::NoChild

        def level: () -> Array[Integer]

        def with_location: (untyped new_location) -> untyped
      end
    end
  end
end
