module Steep
  module Services
    class FileLoader
      attr_reader base_dir: Pathname

      def initialize: (base_dir: Pathname) -> void

      def each_path_in_patterns: (Project::Pattern pattern, ?Array[String] commandline_patterns) { (Pathname) -> void } -> void
                               | (Project::Pattern pattern, ?Array[String] commandline_patterns) -> Enumerator[Pathname, void]

      def load_changes: (untyped pattern, ?untyped command_line_patterns, changes: untyped) -> untyped
    end
  end
end
