module Steep
  module AST
    module Node
      class TypeApplication
        attr_reader location: RBS::Location[untyped, untyped]

        attr_reader node: Parser::AST::Node

        def line: () -> Integer

        def source: () -> String

        def initialize: (RBS::Location[untyped, untyped]) -> void

        def types: (RBS::Resolver::context, Subtyping::Check, Array[Symbol] type_vars) -> (Array[LocatedValue[Types::t]] | RBS::ParsingError | Enumerator[Diagnostic::Signature::Base, void] | nil)

        def types?: (RBS::Resolver::context, Subtyping::Check, Array[Symbol] type_vars) -> Array[LocatedValue[Types::t]]?

        # Yields each RBS type in the type application
        #
        # Raises `RBS::ParsingError` if there is a syntax error.
        #
        def each_rbs_type: (RBS::Resolver::context, Subtyping::Check, Array[Symbol] type_vars) { (RBS::Types::t) -> void } -> void
                         | (RBS::Resolver::context, Subtyping::Check, Array[Symbol] type_vars) -> Enumerator[RBS::Types::t, void]

        @type_str: String?
        def type_str: () -> String

        def type_location: () -> RBS::Location[untyped, untyped]

        # Set the back reference to the `:tapp` node
        def set_node: (Parser::AST::Node) -> void

        def self.parse: (RBS::Location[untyped, untyped]) -> TypeApplication?
      end
    end
  end
end
