module Steep
  module AST
    module Node
      class TypeAssertion
        attr_reader source: String

        attr_reader location: RBS::Location[untyped, untyped]

        def line: () -> Integer

        def initialize: (String source, RBS::Location[untyped, untyped]) -> void

        def type: (RBS::Resolver::context, Types::Factory, Array[Symbol] type_vars) -> (Types::t | RBS::ParsingError)

        def type?: (RBS::Resolver::context, Types::Factory, Array[Symbol] type_vars) -> Types::t?

        def type_str: () -> String

        def self.parse: (String, RBS::Location[untyped, untyped]) -> TypeAssertion?
      end
    end
  end
end
