module Steep
  class CLI
    attr_reader argv: Array[String]

    attr_reader stdout: IO

    attr_reader stdin: IO

    attr_reader stderr: IO

    attr_reader command: Symbol

    def initialize: (stdout: IO, stdin: IO, stderr: IO, argv: Array[String]) -> void

    def self.available_commands: () -> ::Array[Symbol]

    def process_global_options: () -> bool

    def setup_command: () -> bool

    def run: () -> Integer

    interface _CommandWithSteepfile
      def steepfile: () -> Pathname?

      def steepfile=: (Pathname?) -> Pathname?
    end

    def handle_steepfile_option: (OptionParser opts, _CommandWithSteepfile) -> void

    def handle_logging_options: (OptionParser opts) -> void

    def handle_jobs_option: (Drivers::Utils::JobsOption jobs_option, OptionParser opts) -> void

    def setup_jobs_for_ci: (Drivers::Utils::JobsOption) -> void

    def process_init: () -> Integer

    def process_check: () -> Integer

    def process_checkfile: () -> Integer

    def process_stats: () -> Integer

    def process_validate: () -> Integer

    def process_annotations: () -> Integer

    def process_project: () -> Integer

    def process_watch: () -> Integer

    def process_langserver: () -> Integer

    def process_vendor: () -> Integer

    def process_binstub: () -> Integer

    def process_version: () -> Integer

    def process_worker: () -> Integer

    def process_server: () -> Integer
  end
end
