module Steep
  class Project
    attr_reader targets: Array[Target]

    attr_reader steepfile_path: Pathname?

    attr_reader base_dir: Pathname

    attr_accessor global_options: Options

    def initialize: (steepfile_path: Pathname?, ?base_dir: Pathname?) -> void

    def relative_path: (Pathname path) -> Pathname

    def absolute_path: (Pathname path) -> Pathname

    def group_for_path: (Pathname) -> (Target | Group | nil)

    def group_for_source_path: (Pathname path) -> (Target | Group | nil)

    def group_for_signature_path: (Pathname path) -> (Target | Group | nil)

    def group_for_inline_path: (Pathname path) -> (Target | Group | nil)

    def target_for_path: (Pathname) -> Target?

    def target_for_source_path: (Pathname path) -> Target?

    def target_for_signature_path: (Pathname path) -> Target?

    def target_for_inline_path: (Pathname path) -> Target?
  end
end
