class RBS::Location[in RK, in OK]
  def as_lsp_range: () -> LanguageServer::Protocol::Interface::Range::json
end

class Parser::Source::Range
  def as_lsp_range: () -> LanguageServer::Protocol::Interface::Range::json
end
