all_sigs = Pathname.glob("*.rbs")

all_sigs.each do |path|
  target path.basename(".rbs").to_s.to_sym do
    unreferenced!
    signature path.to_s
    configure_code_diagnostics(Steep::Diagnostic::Ruby.all_error)
    implicitly_returns_nil! true
  end
end
