module Steep
  VERSION: String

  def self.logger: () -> (Logger & ActiveSupport::TaggedLogging)

  def self.new_logger: (IO output, Integer? prev_level) -> (Logger & ActiveSupport::TaggedLogging)

  attr_accessor self.log_output: IO

  def self.measure: [A] (String message, ?level: ::Symbol) { () -> A } -> A

  def self.log_error: (Exception exn, ?message: ::String) -> void

  self.@logger: (Logger & ActiveSupport::TaggedLogging)?

  class Sampler
    type sample = [String, Float]
    @samples: Array[sample]

    def initialize: () -> void

    def sample: [A] (String message) { () -> A } -> A

    def count: () -> Integer

    def total: () -> Float

    def slowests: (Integer num) -> Array[sample]

    def average: () -> Float

    def percentile: (Integer p) -> Float
  end

  def self.measure2: [A] (String message, ?level: ::Symbol) { (Sampler) -> A } -> A
end
