interface _Each2[A, B]
  def each: { (A) -> untyped } -> B
end

module A : _Each2[Integer, A]
  def count: () -> Integer
end

module X
  def foo: () -> Integer
end

module Palette
  def self?.defacto_palette: -> Array[Array[Integer]]
  def self.nestopia_palette: -> Array[Array[Integer]]
end
