module Steep
  module Postconditions
    # Shared naming convention for `unconditional.self` markers emitted by
    # `Postconditions::Inferrer` and the matching marker module/class
    # definitions generated by rbs_infer (and any other emitter).
    #
    # Both sides must agree on the marker name string verbatim, otherwise
    # the postcondition references a class that doesn't exist in RBS and
    # `apply_unconditional_postconditions` silently no-ops at apply time.
    # Co-locating the rule here lets us bump it once and have both ends
    # follow.
    #
    # Convention:
    #
    #   marker_name_for("Concerts::Venue", :set_default_name)
    #     # => "::Concerts::Venue::AfterSetDefaultName"
    #
    # i.e. `<ClassName>::After<MethodNamePascal>`, fully qualified.
    # Trailing `?`, `!`, `=` on the method name are stripped — they are
    # not valid identifier characters in a constant name. A method whose
    # name reduces to the empty string after stripping (e.g. `?`) does
    # not get a marker; callers should check for empty input via
    # `valid_method_name?` before composing.
    module MarkerNaming
      # Returns the absolute name of the marker class/module that
      # represents "post-call state for ClassName#method_name". Callers
      # combine this with the original class name to build the narrowed
      # self type, usually via `narrowed_self_type_for`.
      def self.marker_name_for(class_name, method_name)
        relative_class = normalize_class_name(class_name)
        "::#{relative_class}::After#{pascal_case(method_name)}"
      end

      # Returns the full intersection string to drop into the
      # `unconditional.self:` slot of a `.steep_postconditions.yml`
      # entry: `"::ClassName & ::ClassName::AfterMethod"`. The original
      # class is intersected with the marker so the receiver keeps
      # access to its declared methods while gaining the marker's
      # post-call invariants.
      def self.narrowed_self_type_for(class_name, method_name)
        relative_class = normalize_class_name(class_name)
        "::#{relative_class} & #{marker_name_for(class_name, method_name)}"
      end

      # Whether `method_name` produces a non-empty pascal-cased segment.
      # `:set_default_name` → true, `:"="` → false. Use this to gate
      # emission of `unconditional.self` entries.
      def self.valid_method_name?(method_name)
        !pascal_case(method_name).empty?
      end

      def self.normalize_class_name(class_name)
        class_name.to_s.sub(/\A::/, "")
      end

      # `"set_default_name"` → `"SetDefaultName"`. Strips a trailing
      # `?`, `!`, or `=` first since those aren't valid in a constant
      # identifier. Empty segments (e.g. from a leading `_`) become
      # empty strings and are dropped on join.
      def self.pascal_case(method_name)
        sanitized = method_name.to_s.sub(/[?!=]\z/, "")
        sanitized.split("_").map { |part| capitalize_first(part) }.join
      end

      def self.capitalize_first(part)
        return part if part.empty?
        "#{part[0].to_s.upcase}#{part[1..].to_s}"
      end
    end
  end
end
