#!/usr/bin/env ruby

require 'pathname'

$LOAD_PATH << Pathname(__dir__) + "../lib"

require 'steep'
require 'steep/cli'

# A type check runs long enough to pay the compilation back: it takes around 15% off the type
# checking of a project the size of Steep itself, and less than that when the workers already
# keep every core busy. It costs some memory in each of the processes, and `STEEP_YJIT=0`
# turns it off.
#
# The files above are loaded first, so that the code that runs once while they load doesn't
# take up the code region.
if ENV['STEEP_YJIT'] != '0' && defined?(RubyVM::YJIT) && RubyVM::YJIT.respond_to?(:enable)
  RubyVM::YJIT.enable
end

begin
  exit Steep::CLI.new(argv: ARGV.dup, stdout: STDOUT, stderr: STDERR, stdin: STDIN).run
rescue => exn
  STDERR.puts exn.inspect
  exn.backtrace.each do |t|
    STDERR.puts "  #{t}"
  end
  exit 2
end
