module Steep
  module Subtyping
    class Relation[T]
      attr_reader sub_type: T

      attr_reader super_type: T

      def initialize: (sub_type: T, super_type: T) -> void

      def hash: () -> untyped

      def ==: (untyped other) -> untyped

      alias eql? ==

      def to_s: () -> ::String

      def to_ary: () -> [T, T]

      def type?: () -> untyped

      def interface?: () -> untyped

      def method?: () -> untyped

      def function?: () -> untyped

      def params?: () -> untyped

      def block?: () -> untyped

      def assert_type: (untyped `type`) -> (untyped | nil)

      def type!: () -> untyped

      def interface!: () -> untyped

      def method!: () -> untyped

      def function!: () -> untyped

      def params!: () -> untyped

      def block!: () -> untyped

      def map: [S] () { (T) -> S } -> Relation[S]

      def flip: () -> Relation[T]
    end
  end
end
