module Steep
  module Subtyping
    class VariableVariance
      attr_reader covariants: untyped

      attr_reader contravariants: untyped

      def initialize: (covariants: untyped, contravariants: untyped) -> void

      def covariant?: (untyped var) -> untyped

      def contravariant?: (untyped var) -> untyped

      def invariant?: (untyped var) -> untyped

      def self.from_method_type: (untyped method_type) -> untyped

      def self.add_params: (untyped params, block: untyped, covariants: untyped, contravariants: untyped) -> untyped

      def self.add_type: (untyped `type`, variance: untyped, covariants: untyped, contravariants: untyped) -> untyped
    end
  end
end
