module Steep
  module Drivers
    class Check
      module LSP = LanguageServer::Protocol

      attr_reader stdout: IO

      attr_reader stderr: IO

      attr_reader command_line_patterns: Array[String]

      attr_accessor with_expectations_path: Pathname?

      attr_accessor save_expectations_path: Pathname?

      attr_accessor severity_level: Diagnostic::LSPFormatter::severity

      attr_reader jobs_option: Utils::JobsOption

      attr_reader active_group_names: Array[[Symbol, Symbol | true | nil]]

      attr_accessor type_check_code: bool

      attr_accessor validate_group_signatures: bool

      attr_accessor validate_project_signatures: bool

      attr_accessor validate_library_signatures: bool

      attr_accessor formatter: ("code" | "github")

      attr_accessor use_daemon: bool

      include Utils::DriverHelper

      def initialize: (stdout: IO, stderr: IO) -> void

      def run: () -> Integer

      def print_expectations: (project: Project, all_files: Array[Pathname], expectations_path: Pathname, notifications: Array[untyped]) -> Integer

      def save_expectations: (project: Project, all_files: Array[Pathname], expectations_path: Pathname, notifications: Array[untyped]) -> Integer

      def print_result: (project: Project, notifications: Array[untyped]) -> Integer

      # Returns true if the given target is active for this invocation
      def active_group?: (Project::Target | Project::Group) -> bool

      def load_files: (Server::TargetGroupFiles, Project::Target, Project::Target | Project::Group, params: Server::CustomMethods::TypeCheck::params) -> void

      private

      def run_with_server: () -> Integer

      def run_standard_check: () -> Integer

      def print_typecheck_result: (project: Project, diagnostic_notifications: Array[untyped], error_messages: Array[String]) -> Integer

      def build_typecheck_params: (Project project) -> Server::CustomMethods::TypeCheck::params

      def wait_for_daemon: (?timeout: Integer) -> bool
    end
  end
end
