module Steep
  module Drivers
    class Checkfile
      module LSP = LanguageServer::Protocol

      attr_reader stdout: IO

      attr_reader stderr: IO

      attr_reader command_line_args: Array[String]

      include Utils::DriverHelper

      attr_accessor all_rbs: bool

      attr_accessor all_ruby: bool

      attr_reader stdin_input: Hash[Pathname, String]

      attr_reader jobs_option: Utils::JobsOption

      def initialize: (stdout: IO, stderr: IO) -> void

      def run: () -> Integer
    end
  end
end
