module Steep
  module Drivers
    class DiagnosticPrinter
      module LSP = LanguageServer::Protocol

      attr_reader stdout: IO

      attr_reader buffer: RBS::Buffer

      attr_reader formatter: BaseFormatter

      def initialize: (stdout: IO, buffer: RBS::Buffer, ?formatter: String) -> void

      def print: (Hash[Symbol, untyped] diagnostic, ?prefix: String, ?source: bool) -> void
    end
  end
end
