module Steep
  module Drivers
    class Langserver
      attr_reader stdout: IO

      attr_reader stderr: IO

      attr_reader stdin: IO

      attr_reader write_mutex: Thread::Mutex

      attr_reader type_check_queue: Thread::Queue

      attr_reader type_check_thread: Thread

      attr_reader jobs_option: Utils::JobsOption

      attr_accessor refork: bool

      attr_accessor command_socket: bool

      include Utils::DriverHelper

      def initialize: (stdout: untyped, stderr: untyped, stdin: untyped) -> void

      @writer: LanguageServer::Protocol::Transport::Io::Writer?

      def writer: () -> LanguageServer::Protocol::Transport::Io::Writer

      @reader: LanguageServer::Protocol::Transport::Io::Reader?

      def reader: () -> LanguageServer::Protocol::Transport::Io::Reader

      @project: Project
      def project: () -> Project

      def run: () -> Integer

      # Starts accepting `steep query`/`steep check` connections on the UNIX socket
      #
      # Returns `nil` when the command socket is disabled, is not supported on the platform,
      # or is already served by another process.
      #
      def start_command_socket: (Server::Master master) -> Server::CommandSocket?
    end
  end
end
