module Steep
  module Drivers
    class PrintProject
      attr_reader stdout: untyped

      attr_reader stderr: untyped

      include Utils::DriverHelper

      def initialize: (stdout: untyped, stderr: untyped) -> void

      def run: () -> 0
    end
  end
end
