module Steep
  module Drivers
    class PrintProject
      attr_reader stdout: IO

      attr_reader stderr: IO

      include Utils::DriverHelper

      def initialize: (stdout: IO, stderr: IO) -> void

      def run: () -> Integer
    end
  end
end
