module Steep
  module Drivers
    class StartServer
      attr_reader stdout: IO

      attr_reader stderr: IO

      def initialize: (stdout: IO, stderr: IO) -> void

      def run: () -> Integer
    end
  end
end
