module Steep
  module Signature
    class Validator
      Location: singleton(RBS::Location)

      Declarations: singleton(RBS::AST::Declarations)

      attr_reader checker: Subtyping::Check

      @errors: Array[Diagnostic::Signature::Base]

      @type_name_resolver: RBS::Resolver::TypeNameResolver?

      @validator: RBS::Validator?

      # Stack of `self_type`, `class_type`, `instance_type` tuple
      #
      attr_reader context: Array[[AST::Types::t?, AST::Types::t?, AST::Types::t?]]

      def latest_context: -> [AST::Types::t?, AST::Types::t?, AST::Types::t?]

      def push_context: [T] (?self_type: AST::Types::t?, ?class_type: AST::Types::t?, ?instance_type: AST::Types::t?) { () -> T } -> T

      def initialize: (checker: Subtyping::Check) -> void

      def has_error?: () -> bool

      def no_error?: () -> bool

      def each_error: () { (Diagnostic::Signature::Base) -> void } -> void
                    | () -> Enumerator[Diagnostic::Signature::Base, void]

      def env: () -> RBS::Environment

      def builder: () -> RBS::DefinitionBuilder

      def type_name_resolver: () -> RBS::Resolver::TypeNameResolver

      def validator: () -> RBS::Validator

      def factory: () -> AST::Types::Factory

      def validate: () -> void

      # Validate type parameters
      #
      # 1. References from default type to optional type parameter is error
      # 2. The default type should satisfy the upper bound constraint
      #
      def validate_type_params: (RBS::TypeName, Array[RBS::AST::TypeParam]) -> void

      # Validate type application constraints
      #
      # Doesn't validate descendant types.
      #
      private def validate_type_application_constraints: (RBS::TypeName type_name, Array[RBS::AST::TypeParam] type_params, Array[RBS::Types::t] type_args, location: RBS::Location[untyped, untyped]?) -> void

      # Validate type application
      #
      # Doesn't validate descendant types.
      #
      private def validate_type_application: (RBS::Types::t) -> void

      # Validate if type name is deprecated
      #
      private def validate_type_name_deprecation: (RBS::TypeName, RBS::Location[untyped, untyped]) -> void

      # Validate a type and its descendants
      #
      def validate_type: (RBS::Types::t `type`) -> void

      # Validate a type, and calls the method with its descendants
      #
      def validate_type_0: (RBS::Types::t) -> void

      def ancestor_to_type: (RBS::Definition::Ancestor::t ancestor) -> (AST::Types::Name::Interface | AST::Types::Name::Instance)

      def mixin_constraints: (RBS::Definition definition, Array[RBS::Definition::Ancestor::Instance] mixin_ancestors, immediate_self_types: Array[RBS::Definition::Ancestor::t]?) -> Array[[Subtyping::Relation[AST::Types::t], RBS::Definition::Ancestor::Instance]]

      def each_method_type: (RBS::Definition) { (RBS::Definition::Method, RBS::MethodType) -> void } -> void

      def each_variable_type: (RBS::Definition) { (RBS::Types::t) -> void } -> void

      def validate_definition_type: (RBS::Definition) -> void

      def validate_method_type: (RBS::Definition, RBS::Definition::Method, RBS::MethodType) -> void

      def validate_type_guard_annotation: (RBS::Definition, RBS::MethodType, RBS::AST::Annotation) -> void

      def context_from: (RBS::TypeName) -> RBS::Resolver::context

      def validate_one_class: (RBS::TypeName) -> void

      def validate_ancestor_application: (RBS::TypeName, RBS::Definition::Ancestor::Instance ancestor) -> void

      def validate_one_interface: (RBS::TypeName) -> void

      def validate_decl: () -> void

      def validate_const: () -> void

      def validate_one_constant: (RBS::TypeName name, RBS::Environment::ConstantEntry entry) -> void

      def validate_global: () -> void

      def validate_one_global: (Symbol name, RBS::Environment::GlobalEntry) -> void

      # Validate type alias
      #
      # 1. Make sure the outer namespace of given `name` exists
      # 2. Make sure the type alias is valid with respect to `RBS::Validator`
      #
      def validate_one_alias: (RBS::TypeName name, ?RBS::Environment::TypeAliasEntry entry) -> void

      def validate_one_class_decl: (RBS::TypeName, RBS::Environment::ClassEntry | RBS::Environment::ModuleEntry) -> void

      def validate_one_class_alias: (RBS::TypeName, RBS::Environment::ClassAliasEntry | RBS::Environment::ModuleAliasEntry) -> void

      def validate_alias: () -> void

      def rescue_validation_errors: (?RBS::TypeName? type_name) { () -> void } -> void
    end
  end
end
