use Steep::Diagnostic::Ruby::template as diagnostics_config

module Steep
  class Project
    class DSL
      interface _WithProject
        def project: () -> Project
      end

      module LibraryOptions : _WithProject
        @library_configured: bool

        attr_reader libraries: Array[String]

        attr_reader stdlib_root: Pathname?

        attr_reader core_root: Pathname?

        attr_reader repo_paths: Array[Pathname]

        # Attribute to keep track of collection configuration
        #
        # * `Pathname` means loading the configuration from the path
        # * `nil` means no configuration is given
        # * `false` means rbs-collection is disabled
        #
        attr_reader collection_config_path: Pathname | false | nil

        # Set up stdlib paths
        #
        def stdlib_path: (core_root: String, stdlib_root: String) -> void

        # Add repository paths
        #
        def repo_path: (*String paths) -> void

        # Set the `rbs_collection.yaml` path
        #
        def collection_config: (Pathname path) -> void

        # Disable `rbs collection`
        #
        def disable_collection: () -> void

        # Add library
        def library: (*String args) -> void

        def to_library_options: () -> Options

        def library_configured?: () -> bool
      end

      module WithPattern
        attr_reader sources: Array[String]

        attr_reader signatures: Array[String]

        attr_reader ignored_sources: Array[String]

        attr_reader ignored_signatures: Array[String]

        @ext: String?

        def check: (*String args) -> void

        def ext: (String ext) -> void

        def ignore: (*String args) -> void

        def signature: (*String args) -> void

        def ignore_signature: (*String args) -> void

        def source_pattern: () -> Pattern

        def signature_pattern: () -> Pattern
      end

      class TargetDSL
        attr_reader name: Symbol

        attr_reader unreferenced: bool

        attr_reader groups: Array[GroupDSL]

        attr_reader implicitly_returns_nil: bool

        include LibraryOptions

        include WithPattern

        attr_reader project: Project

        def initialize: (Symbol name, project: Project) -> void

        def initialize_copy: (instance other) -> void

        # Mark the target is not referenced from other targets
        #
        # Use this for test targets so that editing files in this target doesn't involve type checking other targets.
        #
        def unreferenced!: (?bool) -> void

        # Mark the target implicitly returns nil
        #
        def implicitly_returns_nil!: (?bool) -> void

        # Configuration of Ruby code diagnostics
        #
        # The default is `Diagnostic::Ruby.default`.
        #
        attr_reader code_diagnostics_config: diagnostics_config

        # Configure the code diagnostics printing setup.
        #
        # Pass a diagnostics configuration for the target.
        #
        # ```rb
        # configure_code_diagnostics(D::Ruby.lenient)
        # ```
        #
        # Passing a block to modify the configuration is also allowed.
        #
        # ```rb
        # D = Steep::Diagnostic
        #
        # configure_code_diagnostics(D::Ruby.default) do |hash|
        #   # Assign one of :error, :warning, :information, :hint or :nil to error classes.
        #   hash[D::Ruby::UnexpectedPositionalArgument] = :error
        # end
        # ```
        #
        # Omitting the parameter yields current configuration. (Defaults to `Diagnostic::Ruby.default`.)
        #
        # ```rb
        # D = Steep::Diagnostic
        #
        # configure_code_diagnostics do |config|
        #   config[D::Ruby::NoMethod] = nil
        # end
        # ```
        #
        def configure_code_diagnostics: (?diagnostics_config hash) { (diagnostics_config) -> void } -> void
                                      | (diagnostics_config config) -> void

        def group: (interned) ?{ (GroupDSL) [self: GroupDSL] -> void } -> void
      end

      class GroupDSL
        include WithPattern

        attr_reader name: Symbol

        attr_reader target: TargetDSL

        # Configuration of Ruby code diagnostics
        #
        # The default is `nil` to inherit the configuration of the target.
        #
        attr_reader code_diagnostics_config: diagnostics_config?

        def initialize: (Symbol name, TargetDSL) -> void

        # Configure the code diagnostics printing setup
        #
        # Initialize the configuration with `target`'s configuration, and yields the hash to customize.
        #
        # ```rb
        # configure_code_diagnostics() do |config|
        #   config[Steep::Diagnostic::Ruby::NoMethod] = :info
        # end
        # ```
        #
        # Initialize the configuration with `lenient`, and yields the hash to customize.
        #
        # ```rb
        # configure_code_diagnostics(D::Ruby.lenient) do |config|
        #   config[Steep::Diagnostic::Ruby::NoMethod] = :info
        # end
        # ```
        #
        # Passing `nil` resets the current configuration.
        #
        # ```rb
        # configure_code_diagnostics(nil)
        # ```
        #
        def configure_code_diagnostics: (?diagnostics_config hash) { (diagnostics_config) -> void } -> void
                                      | (diagnostics_config? config) -> void
      end

      attr_reader project: Project

      def initialize: (project: Project) -> void

      def self.parse: (Project project, String code, ?filename: String) -> void

      def self.eval: (Project project) { () [self: DSL] -> void } -> void

      include LibraryOptions

      def target: (interned name) ?{ (TargetDSL) [self: TargetDSL] -> void } -> void
    end
  end
end
