use Steep::TypeConstruction::Pair, Steep::TypeInference::LogicTypeInterpreter::Result

module Steep
  module TypeInference
    class Branch
      attr_reader start_env: TypeEnv

      def initialize: (TypeEnv start_env) -> void

      def add_branch: () { (TypeEnv) -> [Result, Pair] } -> void

      
    end
  end
end
