name: Run test on container

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.3', '3.4', '4.0']
        task:
          - test
          - test:output
          - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: none
    - name: Fix permission
      run: |
        gem env gemdir
        chmod 775 `gem env gemdir`/gems
    - name: Run test
      run: |
        git config --global --add safe.directory /__w/steep/steep
        ruby -v
        gem install bundler
        bundle config --global with development
        bin/setup
        bundle exec rake ${{matrix.task}}
  type_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "4.0"
        bundler: none
    - name: Fix permission
      run: |
        gem env gemdir
        chmod 775 `gem env gemdir`/gems
    - name: Type check
      run: |
        git config --global --add safe.directory /__w/steep/steep
        ruby -v
        gem install bundler
        bin/setup
        bin/steep check --validate=library --severity=error
  diagnostics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "4.0"
        bundler: none
    - name: Fix permission
      run: |
        gem env gemdir
        chmod 775 `gem env gemdir`/gems
    - name: Run generator
      run: |
        git config --global --add safe.directory /__w/steep/steep
        ruby -v
        gem install bundler
        bin/setup
        bundle exec ruby bin/generate-diagnostics-docs.rb
        git diff --exit-code HEAD -- manual

