module Steep
  module Interface
    class TypeParam
      type loc = RBS::Location[untyped, untyped]

      type variance = RBS::AST::TypeParam::variance

      attr_reader name: Symbol

      attr_reader upper_bound: AST::Types::t?

      attr_reader variance: variance

      attr_reader unchecked: bool

      attr_reader location: loc?

      def initialize: (name: Symbol, upper_bound: AST::Types::t?, variance: variance, unchecked: bool, ?location: loc?) -> void

      def ==: (untyped other) -> bool

      alias eql? ==

      def hash: () -> Integer

      # Rename the type parameters to fresh names
      #
      # Returns a pair of renamed type parameters and substitution.
      #
      # ```rb
      # TypeParam.rename([`X`, `Y`], [:X, :Y])  # [[`X(0)`, `Y(1)`], `{ X => X(0), Y => Y(1) }`]
      # ```
      #
      def self.rename: (Array[TypeParam] params, ?Array[Symbol] conflicting_names, ?Array[Symbol] new_names) -> [Array[TypeParam], Substitution]

      def to_s: () -> String

      def update: (?name: Symbol, ?upper_bound: AST::Types::t?, ?variance: variance, ?unchecked: bool, ?location: loc?) -> TypeParam

      def subst: (Substitution s) -> TypeParam
    end
  end
end
